[package]
name = "wayM"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.0"
image = "0.24.7"
smithay = "0.3.0"
smithay-client-toolkit = "0.17.0"
wayland-client = "0.31.1"
 